version: '3.3'

services:

  mysqlapp:
    container_name: mysql_container
    build: ./db
    image: assignment/mysql
    ports:
      - 3306:3306
    networks:
      - assignment_network

  javaapp:
    container_name: app_container
    build: ./app
    image: assignment/app
    ports:
      - 8080:8080
    networks:
      - assignment_network

networks: 
  assignment_network:
    driver: bridge