CREATE TABLE todoitem (
id 				INT PRIMARY KEY AUTO_INCREMENT,
name 			VARCHAR(200),
description  	VARCHAR(500),
completed 		BOOLEAN DEFAULT false,
create_date 	DATETIME DEFAULT CURRENT_TIMESTAMP,
update_date		DATETIME DEFAULT CURRENT_TIMESTAMP
);